site_name: Yalin(Eric) Yang's Projects
# site_description: A Python package for interactive mapping with Google Earth Engine
site_author: Yalin(Eric) Yang
site_url: https://gisyaliny.github.io/projects/
copyright: "Copyright &copy; 2022 - 2023 Yalin Yang"

# Repository
repo_name: gisyaliny/projects
repo_url: https://gisyaliny.github.io/projects/

# Configuration
theme:
    language: en
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        # - toc.integrate
        # - navigation.tabs
        - navigation.sections
        - search.highlight
        - search.share
    # custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://gisyaliny.github.io/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/gisyaliny
    # - icon: fontawesome/brands/instagram
    #   link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
  
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - open-in-new-tab
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          allow_errors: false
          ignore: ["conf.py"]
          #   execute: True

nav:
    - Home: index.md
    - Computer Vision:
      - OpenCV:
        - Object Detection: "Computer-Vision/Object-Detection-Using-OpenCV.ipynb"
    - GIS:
      - Web Mapping: "GIS/Python-automation-tutorial.ipynb"
      - Optimal GSS: "GIS/Optimize-GSS-with-tessellation.ipynb"
    - Data Analyst:
      - PowerBI:
        - Sales Summary: "https://app.powerbi.com/view?r=eyJrIjoiNzk2MjY2OTktZjNjOS00YzYzLTg5Y2YtN2Y0NTcxNzAxYmFkIiwidCI6IjhkMjgxZDFkLTljNGQtNGJmNy1iMTZlLTAzMmQxNWRlOWY2YyIsImMiOjN9"
    - Deep-Learning:
      - NLP:
        - Craigslist Rent: "Deep-Learning/NLP/NLP-LSTM.ipynb"
    - Research:
      - Taxi data:
        - Project Intro: "Research/Measuring-the-vibrancy-of-Austin-using-taxi-data/introduction.pdf"
        - Video Intro: "Research/Measuring-the-vibrancy-of-Austin-using-taxi-data/Intro.mp4"
        - Sample Script (Selected):
          - Data Preprocessing: "Research/Measuring-the-vibrancy-of-Austin-using-taxi-data/Data-Clean.ipynb"
          - Page Rank: "Research/Measuring-the-vibrancy-of-Austin-using-taxi-data/PageRank.ipynb"
      - Social Events:
        - Association Mining Overview: "Research/Quantifying-the-impacts-of-POIs-on-human-networks/YalinYang-Poster.pdf"
        - Place Recommendation Systems: "Research/Quantifying-the-impacts-of-POIs-on-human-networks/Enhancing-Place-Recommendation-Systems-using-Social-events.pdf"
        - Web application: "https://storymaps.arcgis.com/stories/546b6e82d701424b8bc2a9a0900786f7"
      - GeoAI foundation model:
        - Project Intro: "Research/GEOAI-Model-Transformation/IGUIDE_Team6.pdf"
        - Script Instruction: "Research/GEOAI-Model-Transformation/instruction.ipynb"
      - Tweets Sensitivity Analysis:
        - Project Intro: "Research/City-Sensitivity-Analysis/Tweets-sentimental.nb.html"
        - Shiny APP download: "Research/City-Sensitivity-Analysis/app2.R"
      - Sleep Quality:
        - Project Intro: "Research/Deciphering-the-Impact-of-Built-Environments-on-Sleep-Quality/Intro.png"
        - Android App Development: "https://gisyaliny.github.io/files/research/GPS%20App%20instructions.pdf"
        - Serverless App development with AWS: "https://gisyaliny.github.io/#researchModal4"
      - Add-in Development For Dislocated Water System:
        - Project Intro: "Research/Add-in-plug-in-Development-For-Dislocated-Water-System-Extraction/intro.ipynb"
        - Script Download: "Research/Add-in-plug-in-Development-For-Dislocated-Water-System-Extraction/ProfileAnalyst1.rar"
      - Traffic Accidents:
        - Project Intro: "Research/Traffic-Accidents-In-Dallas/Intro.pdf"
        - MapMatching (Tranditional): "Research/Traffic-Accidents-In-Dallas/MapMatching.pdf"
        - MapMatching (HMM): "Research/Traffic-Accidents-In-Dallas/MapMatching-HMM.pdf"
      
      

